### ISSUE TITLE
Error: Cannot find module "emailjs-smtp-client-response-parser"

### ISSUE THREAD

**Issue by stdevjorge** [emailjs/emailjs-smtp-client#45]
Hello,

I read this issue: https://github.com/emailjs/emailjs-smtp-client/issues/36

But the error persist today.

Log:
Error: Cannot find module "emailjs-smtp-client-response-parser"
    at webpackMissingModule (http://localhost:8100/build/vendor.js:168532:139)
    at _typeof (http://localhost:8100/build/vendor.js:168532:251)
    at Object._typeof (http://localhost:8100/build/vendor.js:168551:2)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.368 (http://localhost:8100/build/main.js:306:78)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.367 (http://localhost:8100/build/main.js:255:69)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.246 (http://localhost:8100/build/main.js:93:69)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)

**Comment by felixhammerl** [comment]
Hi! Finished it up yesterday, please try again w/ v2.0.0
